URL_PAGE = "https://2011.bolshoi.ru/visit/buyingnew/"
CHROME_DRIVER_PATH = "/Users/i/Downloads/_Python/ChromeDriver_106.0.5249.61/chromedriver"
SEARCH_PHRASE_FOR_PDF_LINK = "2022-12"
WORD_TO_FIND= "щелкунчик"
PIC_PATH = "/Users/i/Dev/personal_dev_algorithms/schedule_pdf_check_bot/pics"
PDF_PATH = "/Users/i/Dev/personal_dev_algorithms/schedule_pdf_check_bot/pdfs"
HTML_PATH = "/Users/i/Dev/personal_dev_algorithms/schedule_pdf_check_bot/htmls"
